<a href="https://colab.research.google.com/github/danielpomboza6/Autonomo_1_Programacion_2/blob/main/STV_Semana7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# STV - Unidad 2, Tema 2, Semana 1  
## Indexación, segmentación, métodos `arg` y KNN con NumPy

**Asignatura:** Programación II  
**Unidad 2:** Manipulación y Análisis de Datos con NumPy  
**Tema 2.2:** Indexación, Segmentación y Manipulación Avanzada  
**Semana 1:** Indexación básica, avanzada, slicing y métodos `arg`

---

### Propósito de la sesión

En esta sesión tutorial práctica se trabajará con arreglos NumPy para seleccionar, segmentar, filtrar y localizar datos relevantes dentro de arreglos unidimensionales y matrices. Al final se implementará un algoritmo **k-Nearest Neighbors (k-NN)** para clasificación usando únicamente NumPy.

### Contenidos prácticos

1. Indexación básica en arreglos 1D.
2. Slicing con `start:stop:step`.
3. Indexación en matrices 2D.
4. Indexación booleana.
5. Métodos `arg`: `argmax`, `argmin`, `argsort`, `argwhere`.
6. Selección eficiente con `argpartition`.
7. Aplicación final: algoritmo k-NN para clasificación.

### Indicaciones generales

- Resolver cada ejercicio en las celdas indicadas.
- No usar ciclos `for` cuando el ejercicio pida una solución vectorizada.
- Comentar brevemente cada resultado importante.
- Mantener el notebook ordenado y con explicaciones en celdas Markdown.

## 0. Preparación del entorno

Ejecute la siguiente celda para importar NumPy y verificar la versión instalada.

In [21]:
import numpy as np

print("Versión de NumPy:", np.__version__)

Versión de NumPy: 2.0.2


# Ejercicio 1. Indexación básica en un arreglo 1D

Una tienda registra las ventas diarias, en dólares, durante una semana.

El arreglo `ventas` contiene las ventas desde lunes hasta domingo:

```python
[Lunes, Martes, Miércoles, Jueves, Viernes, Sábado, Domingo]
```

### Tareas

1. Mostrar la venta del lunes.
2. Mostrar la venta del domingo usando índice negativo.
3. Mostrar la venta del jueves.
4. Calcular la diferencia entre la venta del sábado y la venta del martes.
5. Crear una variable llamada `dia_mayor_interes` que guarde el índice del día viernes.
6. Usar esa variable para mostrar la venta del viernes.

### Pregunta de análisis

¿Por qué es importante recordar que NumPy empieza a contar desde el índice `0`?

In [22]:
import numpy as np

ventas = np.array([80, 95, 100, 120, 130, 160, 140])

# 1. Venta del lunes (primer elemento -> índice 0)
venta_lunes = ventas[0]

# 2. Venta del domingo usando índice negativo (último elemento -> índice -1)
venta_domingo = ventas[-1]

# 3. Venta del jueves (Lunes=0, Martes=1, Miércoles=2, Jueves=3)
venta_jueves = ventas[3]

# 4. Diferencia entre sábado (índice 5) y martes (índice 1)
dif_sab_mar = ventas[5] - ventas[1]

# 5. Índice del viernes (quinto día -> índice 4)
dia_mayor_interes = 4

# 6. Venta del viernes usando la variable anterior
venta_viernes = ventas[dia_mayor_interes]

print(f"Lunes: {venta_lunes}, Domingo: {venta_domingo}, Jueves: {venta_jueves}")
print(f"Diferencia Sábado-Martes: {dif_sab_mar}, Viernes: {venta_viernes}")

Lunes: 80, Domingo: 140, Jueves: 120
Diferencia Sábado-Martes: 65, Viernes: 130


# Ejercicio 2. Slicing en arreglos 1D

Se registran las temperaturas de una ciudad durante 12 horas consecutivas.

```python
[06h, 07h, 08h, ..., 17h]
```

### Tareas

1. Extraer las temperaturas de las primeras 4 horas.
2. Extraer las temperaturas desde la hora 09h hasta la 13h.
3. Extraer las temperaturas cada 2 horas.
4. Extraer las últimas 3 temperaturas.
5. Invertir el arreglo usando slicing.
6. Calcular el promedio de las temperaturas entre 10h y 15h.

### Restricción

Debe usar slicing. No seleccionar elemento por elemento.

In [23]:
temperaturas = np.array([15.2, 16.1, 17.5, 19.0, 20.3, 21.8, 23.1, 24.0, 23.5, 22.1, 20.0, 18.4])

# 1. Primeras 4 horas (índices 0, 1, 2, 3)
primeras_4h = temperaturas[:4]

# 2. Desde 09h hasta 13h. Pista: 06h es índice 0 -> 09h es índice 3, 13h es índice 7.
# El límite superior se pone exclusivo (+1), es decir, 8.
de_09h_a_13h = temperaturas[3:8]

# 3. Cada 2 horas (paso o step = 2)
cada_2h = temperaturas[::2]

# 4. Últimas 3 temperaturas
ultimas_3 = temperaturas[-3:]

# 5. Arreglo invertido
invertido = temperaturas[::-1]

# 6. Promedio entre 10h (índice 4) y 15h (índice 9). Límite exclusivo = 10.
promedio_10_15 = np.mean(temperaturas[4:10])

print("Primeras 4h:", primeras_4h)
print("09h a 13h:", de_09h_a_13h)
print("Cada 2h:", cada_2h)
print("Últimas 3:", ultimas_3)
print("Invertido:", invertido)
print(f"Promedio 10h-15h: {promedio_10_15:.2f}")

Primeras 4h: [15.2 16.1 17.5 19. ]
09h a 13h: [19.  20.3 21.8 23.1 24. ]
Cada 2h: [15.2 17.5 20.3 23.1 23.5 20. ]
Últimas 3: [22.1 20.  18.4]
Invertido: [18.4 20.  22.1 23.5 24.  23.1 21.8 20.3 19.  17.5 16.1 15.2]
Promedio 10h-15h: 22.47


# Ejercicio 3. Indexación en matrices 2D

La siguiente matriz representa las ventas de 4 sucursales durante 5 días.

- Cada fila representa una sucursal.
- Cada columna representa un día.

| Sucursal | Día 1 | Día 2 | Día 3 | Día 4 | Día 5 |
|---|---:|---:|---:|---:|---:|
| Sucursal 0 | 120 | 135 | 150 | 160 | 170 |
| Sucursal 1 | 90 | 100 | 95 | 110 | 105 |
| Sucursal 2 | 200 | 210 | 190 | 220 | 230 |
| Sucursal 3 | 80 | 85 | 88 | 92 | 95 |

### Tareas

1. Seleccionar todas las ventas de la sucursal 0.
2. Seleccionar todas las ventas de la sucursal 2.
3. Seleccionar las ventas del día 3 para todas las sucursales.
4. Seleccionar la venta de la sucursal 2 en el día 4.
5. Extraer las dos primeras sucursales y los tres primeros días.
6. Extraer las últimas dos sucursales y los últimos dos días.
7. Calcular el promedio de ventas por sucursal.
8. Calcular el promedio de ventas por día.

### Pista sobre `axis`

- `axis=0`: operación por columnas.
- `axis=1`: operación por filas.

In [24]:
ventas_matriz = np.array([
    [120, 135, 150, 160, 170],  # Sucursal 0
    [90,  100, 95,  110, 105],  # Sucursal 1
    [200, 210, 190, 220, 230],  # Sucursal 2
    [80,  85,  88,  92,  95]    # Sucursal 3
])

# 1. Sucursal 0 (Fila 0, todas las columnas)
suc_0 = ventas_matriz[0, :]

# 2. Sucursal 2 (Fila 2, todas las columnas)
suc_2 = ventas_matriz[2, :]

# 3. Día 3 para todas las sucursales (Todas las filas, Columna índice 2)
dia_3 = ventas_matriz[:, 2]

# 4. Sucursal 2, día 4 (Fila índice 2, Columna índice 3)
suc2_dia4 = ventas_matriz[2, 3]

# 5. Dos primeras sucursales (filas 0:2) y tres primeros días (columnas 0:3)
sub_matriz_inicio = ventas_matriz[0:2, 0:3]

# 6. Últimas dos sucursales (filas -2:) y últimos dos días (columnas -2:)
sub_matriz_final = ventas_matriz[-2:, -2:]

# 7. Promedio por sucursal (operación a lo largo de las filas -> axis=1)
prom_sucursal = np.mean(ventas_matriz, axis=1)

# 8. Promedio por día (operación a lo largo de las columnas -> axis=0)
prom_dia = np.mean(ventas_matriz, axis=0)

print("Ventas del día 3 (todas las suc):", dia_3)
print("Sucursal 2, Día 4:", suc2_dia4)
print("Promedio por sucursal:", prom_sucursal)
print("Promedio por día:", prom_dia)

Ventas del día 3 (todas las suc): [150  95 190  88]
Sucursal 2, Día 4: 220
Promedio por sucursal: [147. 100. 210.  88.]
Promedio por día: [122.5  132.5  130.75 145.5  150.  ]


# Ejercicio 4. Indexación avanzada con listas

Una empresa desea analizar solamente ciertas sucursales y ciertos días específicos.

Utilice la matriz `ventas_matriz` del ejercicio anterior.

### Tareas

1. Seleccionar únicamente las sucursales 0 y 2.
2. Seleccionar únicamente las sucursales 1 y 3.
3. Seleccionar las columnas correspondientes a los días 1, 3 y 5.
4. Crear un arreglo con los nombres de las sucursales.
5. Usar indexación avanzada para mostrar los nombres de las sucursales seleccionadas en el punto 1.
6. Explicar brevemente en Markdown la diferencia entre slicing e indexación avanzada.

In [25]:
nombres_sucursales = np.array(["Centro", "Norte", "Sur", "Valle"])

# 1. Sucursales 0 y 2 (Filas elegidas mediante lista)
suc_0_2 = ventas_matriz[[0, 2], :]

# 2. Sucursales 1 y 3
suc_1_3 = ventas_matriz[[1, 3], :]

# 3. Columnas correspondientes a los días 1, 3 y 5 (Índices de columna: 0, 2 y 4)
dias_1_3_5 = ventas_matriz[:, [0, 2, 4]]

# 4 y 5. Nombres de las sucursales 0 y 2 usando indexación avanzada
nombres_seleccionados = nombres_sucursales[[0, 2]]

print("Filas 0 y 2:\n", suc_0_2)
print("Días 1, 3 y 5:\n", dias_1_3_5)
print("Nombres de sucursales seleccionadas:", nombres_seleccionados)

Filas 0 y 2:
 [[120 135 150 160 170]
 [200 210 190 220 230]]
Días 1, 3 y 5:
 [[120 150 170]
 [ 90  95 105]
 [200 190 230]
 [ 80  88  95]]
Nombres de sucursales seleccionadas: ['Centro' 'Sur']


# Ejercicio 5. Indexación booleana

Se tiene un conjunto de consumos eléctricos diarios medidos en kWh.

Cada fila representa una vivienda y cada columna representa un día.

### Tareas

1. Filtrar todos los consumos mayores a 18 kWh.
2. Crear una máscara booleana para consumos menores o iguales a 10 kWh.
3. Contar cuántos consumos son mayores a 18 kWh.
4. Calcular el promedio de los consumos mayores a 18 kWh.
5. Seleccionar las viviendas cuyo promedio semanal sea mayor a 15 kWh.
6. Crear una nueva matriz llamada `viviendas_alto_consumo` con esas viviendas.

### Pregunta de análisis

¿Por qué una máscara booleana puede ser más clara que recorrer la matriz con ciclos?

In [26]:
consumo = np.array([
    [12.5, 13.0, 11.8, 14.2, 15.0],
    [8.5,  9.0,  8.8,  9.5,  10.0],
    [20.0, 21.5, 19.8, 22.0, 23.1],
    [15.5, 16.0, 15.8, 17.2, 18.0],
    [6.5,  7.0,  6.8,  7.5,  8.0]
])

# 1. Filtrar todos los consumos mayores a 18 kWh (Devuelve arreglo 1D)
mayores_18 = consumo[consumo > 18]

# 2. Crear una máscara booleana para consumos menores o iguales a 10 kWh
mascara_menores_10 = consumo <= 10

# 3. Cantidad de consumos mayores a 18 kWh (sumar True equivale a contar 1s)
cant_mayores_18 = np.sum(consumo > 18)

# 4. Promedio de los consumos mayores a 18 kWh
prom_mayores_18 = np.mean(mayores_18)

# 5. Viviendas cuyo promedio semanal (por filas -> axis=1) sea mayor a 15 kWh
promedios_viviendas = np.mean(consumo, axis=1)
mascara_viviendas_alto = promedios_viviendas > 15

# 6. Nueva matriz de viviendas de alto consumo (Filas que cumplen el criterio)
viviendas_alto_consumo = consumo[mascara_viviendas_alto, :]

print("Consumos > 18:", mayores_18)
print("Cantidad de consumos > 18:", cant_mayores_18)
print(f"Promedio de consumos > 18: {prom_mayores_18:.2f}")
print("Matriz de viviendas de alto consumo:\n", viviendas_alto_consumo)

Consumos > 18: [20.  21.5 19.8 22.  23.1]
Cantidad de consumos > 18: 5
Promedio de consumos > 18: 21.28
Matriz de viviendas de alto consumo:
 [[20.  21.5 19.8 22.  23.1]
 [15.5 16.  15.8 17.2 18. ]]


# Ejercicio 6. Métodos `arg`: localizar posiciones relevantes

Los métodos `arg` devuelven posiciones o índices.

- `np.argmax()`: posición del valor máximo.
- `np.argmin()`: posición del valor mínimo.
- `np.argsort()`: índices que ordenan el arreglo.
- `np.argwhere()`: posiciones donde se cumple una condición.

### Contexto

Se registran puntajes de desempeño de 8 modelos predictivos.

### Tareas

1. Encontrar el valor máximo con `np.max`.
2. Encontrar la posición del valor máximo con `np.argmax`.
3. Encontrar el nombre del modelo con mayor puntaje.
4. Encontrar la posición del modelo con menor puntaje.
5. Ordenar los modelos de menor a mayor desempeño usando `np.argsort`.
6. Ordenar los modelos de mayor a menor desempeño.
7. Usar `np.argwhere` para encontrar los modelos con puntaje mayor o igual a 0.85.

### Pregunta de análisis

¿Qué diferencia hay entre saber el valor máximo y saber la posición del valor máximo?

In [27]:
modelos = np.array(["M0", "M1", "M2", "M3", "M4", "M5", "M6", "M7"])
puntajes = np.array([0.72, 0.88, 0.81, 0.90, 0.67, 0.85, 0.79, 0.93])

# 1. Valor máximo
val_max = np.max(puntajes)

# 2. Posición del valor máximo
pos_max = np.argmax(puntajes)

# 3. Nombre del modelo con mayor puntaje
modelo_max = modelos[pos_max]

# 4. Posición del modelo con menor puntaje
pos_min = np.argmin(puntajes)

# 5. Ordenar modelos de menor a mayor desempeño usando np.argsort
indices_ordenados_asc = np.argsort(puntajes)
modelos_ordenados_asc = modelos[indices_ordenados_asc]

# 6. Ordenar modelos de mayor a menor desempeño (invirtiendo el resultado anterior)
modelos_ordenados_desc = modelos[indices_ordenados_asc[::-1]]

# 7. Posiciones de modelos con puntaje >= 0.85 (np.argwhere)
posiciones_altas = np.argwhere(puntajes >= 0.85)

print(f"Máximo: {val_max} en la posición {pos_max} ({modelo_max})")
print("Modelos de menor a mayor:", modelos_ordenados_asc)
print("Modelos de mayor a menor:", modelos_ordenados_desc)
print("Índices donde puntaje >= 0.85:\n", posiciones_altas.flatten())

Máximo: 0.93 en la posición 7 (M7)
Modelos de menor a mayor: ['M4' 'M0' 'M6' 'M2' 'M5' 'M1' 'M3' 'M7']
Modelos de mayor a menor: ['M7' 'M3' 'M1' 'M5' 'M2' 'M6' 'M0' 'M4']
Índices donde puntaje >= 0.85:
 [1 3 5 7]


# Ejercicio 7. Métodos `arg` con matrices y `axis`

Ahora se tiene una matriz donde cada fila representa un modelo y cada columna representa una métrica.

Columnas:

```python
[accuracy, precision, recall, f1_score]
```

### Tareas

1. Encontrar, para cada modelo, la métrica donde obtiene su mejor resultado.
2. Encontrar, para cada métrica, el modelo con mejor resultado.
3. Mostrar los nombres de las métricas ganadoras por modelo.
4. Mostrar los nombres de los modelos ganadores por métrica.
5. Encontrar la posición plana del valor máximo de toda la matriz con `np.argmax`.
6. Convertir esa posición plana a fila y columna con `np.unravel_index`.
7. Interpretar qué modelo y qué métrica corresponden al valor máximo global.

In [28]:
metricas = np.array(["accuracy", "precision", "recall", "f1_score"])
modelos = np.array(["Modelo A", "Modelo B", "Modelo C", "Modelo D"])

resultados = np.array([
    [0.82, 0.80, 0.78, 0.79],
    [0.88, 0.84, 0.86, 0.85],
    [0.91, 0.89, 0.87, 0.88],
    [0.79, 0.82, 0.76, 0.78]
])

# 1. Mejor métrica por modelo (Buscamos la mejor columna por cada fila -> axis=1)
mejor_metrica_por_modelo_idx = np.argmax(resultados, axis=1)

# 2. Mejor modelo por métrica (Buscamos la mejor fila por cada columna -> axis=0)
mejor_modelo_por_metrica_idx = np.argmax(resultados, axis=0)

# 3. Nombres de métricas ganadoras por modelo
nombres_metricas_ganadoras = metricas[mejor_metrica_por_modelo_idx]

# 4. Nombres de modelos ganadores por métrica
nombres_modelos_ganadores = modelos[mejor_modelo_por_metrica_idx]

# 5. Posición plana del máximo global
idx_plano_max = np.argmax(resultados)

# 6. Convertir posición plana a fila y columna coordinada de la matriz
fila_max, col_max = np.unravel_index(idx_plano_max, resultados.shape)

# 7. Interpretar modelo y métrica del máximo global
modelo_global = modelos[fila_max]
metrica_global = metricas[col_max]
valor_global = resultados[fila_max, col_max]

print("Mejor métrica para cada modelo:", dict(zip(modelos, nombres_metricas_ganadoras)))
print("Mejor modelo para cada métrica:", dict(zip(metricas, nombres_modelos_ganadores)))
print(f"El valor máximo global es {valor_global}, que pertenece al '{modelo_global}' en la métrica '{metrica_global}'.")

Mejor métrica para cada modelo: {np.str_('Modelo A'): np.str_('accuracy'), np.str_('Modelo B'): np.str_('accuracy'), np.str_('Modelo C'): np.str_('accuracy'), np.str_('Modelo D'): np.str_('precision')}
Mejor modelo para cada métrica: {np.str_('accuracy'): np.str_('Modelo C'), np.str_('precision'): np.str_('Modelo C'), np.str_('recall'): np.str_('Modelo C'), np.str_('f1_score'): np.str_('Modelo C')}
El valor máximo global es 0.91, que pertenece al 'Modelo C' en la métrica 'accuracy'.


# Ejercicio 8. `argpartition`: selección eficiente de top-k

`np.argpartition()` permite encontrar rápidamente los `k` valores menores o mayores sin ordenar completamente todo el arreglo.

Esto es útil cuando se necesita seleccionar:

- Los `k` mejores modelos.
- Los `k` errores más grandes.
- Las `k` ventas más altas.
- Los `k` vecinos más cercanos en k-NN.

### Tareas

Dado el arreglo de errores de predicción:

1. Encontrar los índices de los 3 errores más pequeños usando `argpartition`.
2. Mostrar los valores de esos errores.
3. Ordenar esos 3 errores de menor a mayor.
4. Encontrar los índices de los 2 errores más grandes usando `argpartition`.
5. Mostrar esos errores ordenados de mayor a menor.
6. Explicar cuándo conviene usar `argpartition` en lugar de `argsort`.

### Restricción

No use `np.argsort` sobre todo el arreglo para seleccionar inicialmente los candidatos. Puede usar `argsort` solo después, sobre el subconjunto seleccionado, para presentarlo ordenado.

In [29]:
errores = np.array([0.45, 0.12, 0.88, 0.30, 0.75, 0.10, 0.60, 0.22, 0.95, 0.18])

# 1. Índices de los 3 errores más pequeños
k = 3
indices_3_menores = np.argpartition(errores, k)[:k]

# 2. Valores de esos errores
valores_3_menores = errores[indices_3_menores]

# 3. Ordenar esos 3 errores de menor a mayor
orden_menores = np.argsort(valores_3_menores)
indices_3_menores_ord = indices_3_menores[orden_menores]
valores_3_menores_ord = valores_3_menores[orden_menores]

# 4. Índices de los 2 errores más grandes usando argpartition
k_mayores = 2
# Tomamos los últimos 'k_mayores' elementos de la partición
indices_2_mayores = np.argpartition(errores, -k_mayores)[-k_mayores:]

# 5. Errores grandes ordenados de mayor a menor
valores_2_mayores = errores[indices_2_mayores]
orden_mayores = np.argsort(valores_2_mayores)[::-1] # Invertido para mayor a menor
indices_2_mayores_ord = indices_2_mayores[orden_mayores]
valores_2_mayores_ord = valores_2_mayores[orden_mayores]

print(f"Los {k} menores errores (ordenados): {valores_3_menores_ord} en índices {indices_3_menores_ord}")
print(f"Los {k_mayores} mayores errores (ordenados): {valores_2_mayores_ord} en índices {indices_2_mayores_ord}")

Los 3 menores errores (ordenados): [0.1  0.12 0.18] en índices [5 1 9]
Los 2 mayores errores (ordenados): [0.95 0.88] en índices [8 2]


# Ejercicio 9. Caso aplicado: selección de sensores críticos

Una planta de producción tiene sensores que registran vibración promedio en diferentes máquinas. Un valor alto de vibración puede indicar posible falla mecánica.

Cada posición del arreglo representa un sensor.

### Tareas

1. Identificar el sensor con mayor vibración.
2. Identificar los 4 sensores con mayor vibración usando `argpartition`.
3. Ordenar esos sensores críticos de mayor a menor vibración.
4. Crear un reporte en pantalla con el formato:

```text
Sensor S03 -> Vibración: 7.80
```

5. Filtrar todos los sensores con vibración mayor a 6.0 usando indexación booleana.
6. Comparar los resultados obtenidos con `argpartition` y con la máscara booleana.

### Pregunta de análisis

¿Qué diferencia práctica existe entre pedir los 4 sensores más críticos y pedir todos los sensores que superen un umbral?

In [30]:
sensores = np.array(["S00", "S01", "S02", "S03", "S04", "S05", "S06", "S07", "S08", "S09"])
vibracion = np.array([2.5, 5.1, 3.8, 7.8, 6.4, 4.2, 8.1, 1.9, 6.9, 5.7])

# 1. Sensor con mayor vibración
sensor_max = sensores[np.argmax(vibracion)]

# 2. Los 4 sensores con mayor vibración usando argpartition (-4 extrae los 4 más grandes)
idx_4_criticos = np.argpartition(vibracion, -4)[-4:]

# 3. Ordenar esos sensores críticos de mayor a menor
valores_4_criticos = vibracion[idx_4_criticos]
orden_critico = np.argsort(valores_4_criticos)[::-1]

idx_4_criticos_ord = idx_4_criticos[orden_critico]

# 4. Reporte en pantalla
print("=== REPORTE DE SENSORES CRÍTICOS ===")
for idx in idx_4_criticos_ord:
    print(f"Sensor {sensores[idx]} -> Vibración: {vibracion[idx]:.2f}")

# 5. Filtrar todos los sensores con vibración mayor a 6.0 usando indexación booleana
mascara_umbral = vibracion > 6.0
sensores_umbral = sensores[mascara_umbral]
vibraciones_umbral = vibracion[mascara_umbral]

print("\n=== SENSORES QUE SUPERAN EL UMBRAL DE 6.0 ===")
for s, v in zip(sensores_umbral, vibraciones_umbral):
    print(f"Sensor {s} -> Vibración: {v:.2f}")

=== REPORTE DE SENSORES CRÍTICOS ===
Sensor S06 -> Vibración: 8.10
Sensor S03 -> Vibración: 7.80
Sensor S08 -> Vibración: 6.90
Sensor S04 -> Vibración: 6.40

=== SENSORES QUE SUPERAN EL UMBRAL DE 6.0 ===
Sensor S03 -> Vibración: 7.80
Sensor S04 -> Vibración: 6.40
Sensor S06 -> Vibración: 8.10
Sensor S08 -> Vibración: 6.90


# Ejercicio 10. Preparación para clasificación: separar características y etiquetas

En clasificación supervisada, normalmente tenemos:

- `X`: matriz de características.
- `y`: vector de etiquetas.

Cada fila de `X` representa una observación.  
Cada columna de `X` representa una variable.

### Contexto

Se tiene un pequeño conjunto de datos de frutas. Cada fruta se describe mediante:

1. Peso en gramos.
2. Diámetro en centímetros.
3. Intensidad de color en una escala de 0 a 10.

La etiqueta indica si la fruta es:

- `"manzana"`
- `"naranja"`
- `"pera"`

### Tareas

1. Mostrar la forma de `X`.
2. Mostrar la forma de `y`.
3. Seleccionar la primera fruta.
4. Seleccionar solamente la columna de peso.
5. Seleccionar solamente las columnas de diámetro e intensidad de color.
6. Seleccionar las frutas cuya intensidad de color sea mayor a 7.
7. Seleccionar las etiquetas correspondientes a esas frutas.

In [31]:
X = np.array([
    [150, 7.0, 8.5],
    [160, 7.2, 8.0],
    [140, 6.8, 8.8],
    [180, 7.8, 6.5],
    [190, 8.0, 6.2],
    [175, 7.6, 6.8],
    [130, 6.5, 5.5],
    [135, 6.7, 5.8],
    [128, 6.3, 5.2]], dtype=float)

y = np.array([
    "manzana", "manzana", "manzana",
    "naranja", "naranja", "naranja",
    "pera", "pera", "pera"])

# 1. Forma de X
forma_X = X.shape

# 2. Forma de y
forma_y = y.shape

# 3. Seleccionar la primera fruta (Fila índice 0)
primera_fruta = X[0, :]

# 4. Seleccionar solamente la columna de peso (Columna índice 0)
columna_peso = X[:, 0]

# 5. Seleccionar solamente las columnas de diámetro e intensidad de color (Slicing 1:)
columnas_resto = X[:, 1:]

# 6. Frutas cuya intensidad de color (columna índice 2) sea mayor a 7
mascara_color = X[:, 2] > 7
frutas_intensas = X[mascara_color, :]

# 7. Etiquetas correspondientes a esas frutas
etiquetas_intensas = y[mascara_color]

print("Forma de X:", forma_X, "| Forma de y:", forma_y)
print("Características de la primera fruta:", primera_fruta)
print("Frutas con intensidad de color > 7:\n", frutas_intensas)
print("Etiquetas de frutas con intensidad > 7:", etiquetas_intensas)

Forma de X: (9, 3) | Forma de y: (9,)
Características de la primera fruta: [150.    7.    8.5]
Frutas con intensidad de color > 7:
 [[150.    7.    8.5]
 [160.    7.2   8. ]
 [140.    6.8   8.8]]
Etiquetas de frutas con intensidad > 7: ['manzana' 'manzana' 'manzana']


# Ejercicio final. Algoritmo k-NN para clasificación con NumPy

## Objetivo

Implementar desde cero un algoritmo **k-Nearest Neighbors (k-NN)** para clasificar una nueva fruta usando solamente NumPy.

## Idea del algoritmo

El algoritmo k-NN clasifica una nueva observación siguiendo estos pasos:

1. Recibe una observación nueva.
2. Calcula la distancia entre esa observación y todas las observaciones conocidas.
3. Selecciona los `k` vecinos más cercanos.
4. Revisa las etiquetas de esos vecinos.
5. Asigna la clase más frecuente entre los vecinos.

## Dataset

Usaremos el dataset de frutas del ejercicio anterior.

Cada fruta tiene tres características:

```text
[peso, diámetro, intensidad_color]
```

## Nueva fruta a clasificar

```python
nueva_fruta = np.array([155, 7.1, 8.2])
```

A simple vista, esta fruta parece cercana a las manzanas, pero el algoritmo debe decidirlo mediante distancias.

---

## Parte A. Cálculo de distancias

### Tareas

1. Crear la variable `nueva_fruta`.
2. Calcular la diferencia entre cada fila de `X` y `nueva_fruta`.
3. Elevar las diferencias al cuadrado.
4. Sumar por fila.
5. Aplicar raíz cuadrada para obtener la distancia euclidiana.
6. Verificar que el resultado tenga una distancia por cada muestra del dataset.

### Fórmula

Para dos puntos \(a\) y \(b\):

\[
d(a,b) = \sqrt{\sum (a_i - b_i)^2}
\]

In [32]:
nueva_fruta = np.array([155, 7.1, 8.2])

# 1. Diferencias entre X y nueva_fruta
diferencias = X - nueva_fruta

# 2. Diferencias al cuadrado

diferencias_cuadrado = diferencias ** 2
# 3. Suma por fila
suma_filas = np.sum(diferencias_cuadrado, axis=1)

# 4. Raíz cuadrada: distancias euclidianas
distancias = np.sqrt(suma_filas)

# 5. Verifique la forma de las distancias
print("Forma de las distancias:", distancias.shape)
print("Distancias obtenidas para cada muestra:\n", distancias)

Forma de las distancias: (9,)
Distancias obtenidas para cada muestra:
 [ 5.00999002  5.0049975  15.01499251 25.06750885 35.06864697 20.0551739
 25.15253466 20.14745642 27.17793222]


## Parte B. Selección de los k vecinos más cercanos

Ahora debe seleccionar los `k` vecinos más cercanos usando `np.argpartition`.

### Tareas

1. Definir `k = 3`.
2. Obtener los índices de los `k` vecinos más cercanos.
3. Mostrar las distancias de esos vecinos.
4. Mostrar las etiquetas de esos vecinos.
5. Ordenar los vecinos seleccionados de menor a mayor distancia para presentarlos mejor.

### Importante

Use `argpartition` para seleccionar los vecinos.  
Después puede usar `argsort` solo sobre el subconjunto seleccionado para ordenar la presentación.

In [33]:
k = 3

# 1. Índices de los k vecinos más cercanos usando argpartition

indices_k = np.argpartition(distancias, k)[:k]
# 2. Distancias de los vecinos

distancias_vecinos = distancias[indices_k]
# 3. Etiquetas de los vecinos

etiquetas_vecinos = y[indices_k]
# 4. Ordenar los vecinos seleccionados por distancia
orden_relativo = np.argsort(distancias_vecinos)

indices_vecinos_ordenados = indices_k[orden_relativo]
distancias_vecinos_ordenados = distancias_vecinos[orden_relativo]
etiquetas_vecinos_ordenados = etiquetas_vecinos[orden_relativo]

print("Índices de los vecinos más cercanos:", indices_vecinos_ordenados)
print("Distancias correspondientes:", distancias_vecinos_ordenados)
print("Etiquetas correspondientes:", etiquetas_vecinos_ordenados)

Índices de los vecinos más cercanos: [1 0 2]
Distancias correspondientes: [ 5.0049975   5.00999002 15.01499251]
Etiquetas correspondientes: ['manzana' 'manzana' 'manzana']


## Parte C. Votación mayoritaria

Una vez seleccionados los vecinos, se debe determinar la clase más frecuente.

### Tareas

1. Usar `np.unique` con `return_counts=True` sobre las etiquetas de los vecinos.
2. Identificar la etiqueta con mayor frecuencia.
3. Mostrar la clase predicha para `nueva_fruta`.

### Pista

Puede usar:

```python
clases, conteos = np.unique(etiquetas_vecinos, return_counts=True)
```

Luego puede aplicar `np.argmax(conteos)` para encontrar la clase ganadora.

In [34]:
# 1. Obtener clases y conteos
clases, conteos = np.unique(etiquetas_vecinos_ordenados, return_counts=True)

# 2. Índice de la clase ganadora
idx_ganadora = np.argmax(conteos)

# 3. Clase predicha
clase_predicha = clases[idx_ganadora]

# 4. Mostrar resultado final
print("Conteo de clases en el vecindario:", dict(zip(clases, conteos)))
print(f"Resultado final: La fruta con características {nueva_fruta} se clasifica como: {clase_predicha}")

Conteo de clases en el vecindario: {np.str_('manzana'): np.int64(3)}
Resultado final: La fruta con características [155.    7.1   8.2] se clasifica como: manzana


## Parte D. Convertir el proceso en una función

Ahora implemente una función llamada `knn_predict`.

### Requisitos de la función

La función debe recibir:

```python
knn_predict(X_train, y_train, x_new, k=3)
```

Y debe retornar:

```python
clase_predicha
```

### Restricciones

- Debe usar NumPy.
- Debe usar `np.argpartition`.
- Debe usar distancia euclidiana.
- No debe usar librerías externas como scikit-learn.

In [35]:
def knn_predict(X_train, y_train, x_new, k=3):
    """
    Clasifica una nueva observación usando k-NN con NumPy.

    Parámetros
    ----------
    X_train : np.ndarray
        Matriz de características de entrenamiento.
    y_train : np.ndarray
        Vector de etiquetas.
    x_new : np.ndarray
        Nueva observación a clasificar.
    k : int
        Número de vecinos más cercanos.

    Retorna
    -------
    str
        Clase predicha.
    """
    # 1. Calcular distancias
    diferencias = X_train - x_new
    diferencias_cuadrado = diferencias ** 2
    suma_filas = np.sum(diferencias_cuadrado, axis=1)
    distancias = np.sqrt(suma_filas)
    # 2. Seleccionar índices de los k vecinos más cercanos
    indices_k = np.argpartition(distancias, k)[:k]
    # 3. Obtener etiquetas de los vecinos
    etiquetas_vecinos = y_train[indices_k]
    # 4. Votación mayoritaria
    clases, conteos = np.unique(etiquetas_vecinos, return_counts=True)
    idx_ganadora = np.argmax(conteos)
    clase_predicha = clases[idx_ganadora]
    # 5. Retornar clase ganadora
    return clase_predicha
    pass


# Prueba de la función
nueva_fruta = np.array([155, 7.1, 8.2])
prediccion = knn_predict(X, y, nueva_fruta, k=3)
print("Predicción:", prediccion)

Predicción: manzana


## Parte E. Clasificar varias frutas nuevas

Ahora clasifique varias frutas nuevas.

### Tareas

1. Crear una matriz `X_nuevas` con 4 frutas nuevas.
2. Aplicar la función `knn_predict` a cada fruta.
3. Guardar las predicciones en un arreglo.
4. Mostrar cada fruta con su clase predicha.

### Datos sugeridos

```python
X_nuevas = np.array([
    [158, 7.1, 8.4],
    [185, 7.9, 6.4],
    [132, 6.6, 5.6],
    [170, 7.4, 7.0]
])
```

### Pregunta de análisis

¿Qué ocurre si se cambia `k=3` por `k=5`?

In [36]:
X_nuevas = np.array([
    [158, 7.1, 8.4],
    [185, 7.9, 6.4],
    [132, 6.6, 5.6],
    [170, 7.4, 7.0]
], dtype=float)

# Clasificar varias frutas
predicciones = []

# Complete el proceso


print("Predicciones:", predicciones)

Predicciones: []


# Reflexión final de la STV

Responda en una celda Markdown:

1. ¿Por qué `argpartition` es útil en k-NN?
2. ¿Qué diferencia hay entre ordenar todas las distancias y seleccionar solo los `k` vecinos?
3. ¿Qué papel cumple la indexación avanzada en la selección de vecinos?
4. ¿Cómo se relaciona esta práctica con la clasificación en ciencia de datos?
5. ¿Qué limitaciones tiene este k-NN simple?

# Rúbrica rápida de revisión

| Criterio | Cumple | Observación |
|---|---|---|
| Usa indexación básica y slicing correctamente |  |  |
| Aplica indexación booleana |  |  |
| Usa `argmax`, `argmin`, `argsort` y `argwhere` |  |  |
| Usa `argpartition` para top-k |  |  |
| Separa características `X` y etiquetas `y` |  |  |
| Implementa distancia euclidiana con NumPy |  |  |
| Implementa k-NN sin scikit-learn |  |  |
| Explica los resultados en Markdown |  |  |